extends CanvasLayer

const DEMO_SECTOR_PATH := "res://modules/demo_selector/demo_selector.tscn"

signal closed

## A reference to the parent scene, removed when the "Quit" option is selected.
@onready var _parent_scene: Node = get_parent()
## Waits for some time after the menu button is pressed before opening/closing it again.
@onready var _cooldown_timer: Timer = $OpenMenuCooldown

@onready var _button_list_container: VBoxContainer = $Control/MarginContainer/PanelContainer/VBoxContainer

var _opened_menu: Node

func _ready() -> void:
	_initialize_buttons()

## Creates buttons for each child of type CanvasLayer
func _initialize_buttons():
	for i in get_child_count():
		var child = get_child(i)
		if child is CanvasLayer:
			child.hide()
			_add_button(i, child.get_button_text())

func _add_button(child_idx: int, text: String) -> void:
	var button = Button.new()
	button.text = text
	button.size_flags_vertical = Control.SIZE_EXPAND_FILL
	button.pressed.connect(open_menu.bind(child_idx))
	_button_list_container.add_child(button)
	var second_to_last_position: int = _button_list_container.get_child_count() - 2
	_button_list_container.move_child(button, second_to_last_position)

func _is_back_input(event: InputEvent) -> bool:
	return (
		event is InputEventKey and event.keycode == KEY_ESCAPE \
		or event is InputEventJoypadButton and event.button_index == JOY_BUTTON_B
	) and event.is_pressed()

func _unhandled_input(event: InputEvent) -> void:
	if _opened_menu != null and _is_back_input(event):
		_opened_menu.hide()
		_opened_menu = null
		_button_list_container.get_child(0).grab_focus()
		get_viewport().set_input_as_handled()
		return

	if event.is_action("game_menu") and event.is_pressed():
		_toggle_visibility()
		get_viewport().set_input_as_handled()

func _toggle_visibility() -> void:
	if visible:
		await $BackgroundBlur.hide_blur().finished
		get_tree().paused = false
		visible = false
		closed.emit()
	else:
		visible = true
		get_tree().paused = true
		_button_list_container.get_child(0).grab_focus()
		await $BackgroundBlur.show_blur().finished

	if _opened_menu != null:
		_opened_menu.hide()
		_opened_menu = null

## Linked to the buttons generated by _initialize_buttons(). Opens (shows) the menu associated to this button.
func open_menu(child_idx: int) -> void:
	_opened_menu = get_child(child_idx)
	_opened_menu.show()
	_opened_menu.grab_focus()

## Unpauses the game and closes (hides) the game menu.
func quit_and_go_to_menu() -> void:
	get_tree().paused = false
	var _scene_loader: SceneLoader = SceneLoader.create_scene_loader(_parent_scene, DEMO_SECTOR_PATH)
