#!/usr/bin/env python3

import fileinput
import re
import argparse
import os
import sys
import html

def remove_newlines(lines):
    return [line.rstrip() for line in lines]

def remove_lines_before_test_report(lines):
    max_lines = len(lines)
    i = 0
    while i < max_lines and not re.search("Testing [0-9]+ scenes.", lines[i]):
        i += 1

    new_lines = []
    while i < max_lines:
        new_lines.append(lines[i])
        i += 1
    return new_lines

def remove_lines_after_test_report(lines):
    max_lines = len(lines)
    i = 0
    new_lines = []
    while i < max_lines and not re.search("Test finished, check for errors", lines[i]):
        new_lines.append(lines[i])
        i += 1
    return new_lines

def delete_empty_tests(lines):
    new_lines = []
    for i in range(len(lines)):
        if re.search("^ - Testing", lines[i]) and i == len(lines) - 1:
            break
        if re.search("^ - Testing", lines[i]) and re.search("^ - Testing", lines[i+1]):
            continue
        else:
            new_lines.append(lines[i])
    return new_lines

def delete_unuseful_errors(lines):
    new_lines = []
    i = 0
    while i < len(lines):
        if re.search('ERROR: Condition "!is_inside_tree\\(\\)"', lines[i]):
            i += 2
        else:
            new_lines.append(lines[i])
            i += 1
    return new_lines

def get_failing_scenes(lines):
    new_lines = []
    for line in lines:
        match = re.match(r" - Testing ([^\s]+)\.\.\.", line)
        if match:
            new_lines.append(match.group(1))

    return new_lines

def get_unique_errors(lines):
    new_lines = []
    for line in lines:
        if re.search('ERROR', line):
            new_lines.append(line)

    return list(set(new_lines))

def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Parses the log file generated by the smoke tests. Used to provide helpful messages from the CI.",
        usage="%(prog)s [--unique-scenes] [--unique-errors] INPUT_FILE",
        epilog="Example: ./script.py --unique-scenes error_log.txt"
    )

    parser.add_argument("--unique-scenes",
                        action="store_true",
                        help="Filter unique scene identifiers")
    parser.add_argument("--unique-errors",
                        action="store_true",
                        help="Filter unique error messages")
    parser.add_argument("--web",
                        action="store_true",
                        help="If true, escapes newline and other non web friendly characters")

    parser.add_argument("input_file",
                        help="Path to the log file to process")

    args = parser.parse_args()

    if not os.path.isfile(args.input_file):
        sys.exit(f"Error: Input file '{args.input_file}' not found or is not a file")

    return args

def escape_json_characters(lines):
    new_lines = [line.replace('"', '\\"') for line in lines]
    return ["\\n".join(new_lines)]

def main():
    args = parse_arguments()

    f = open(args.input_file, "r")
    lines = f.readlines()
    lines = remove_newlines(lines)
    lines = remove_lines_before_test_report(lines)
    lines = remove_lines_after_test_report(lines)

    lines = delete_unuseful_errors(lines)
    lines = delete_empty_tests(lines)

    if args.unique_errors:
        lines = get_unique_errors(lines)
    if args.unique_scenes:
        lines = get_failing_scenes(lines)
    if args.web:
        lines = escape_json_characters(lines)

    for line in lines:
        print(line)

main()
