name: Tests
on:
  schedule:
    # monday, wednesday, friday at 6:00
    - cron: 0 6 * * 1,3,5
  workflow_dispatch:

env:
  GODOT_VERSION: 4.5.1

jobs:
  smoke-test:
    name: Run smoke test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: nokorpo/godot-tests:4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Run test
        id: smoke-test
        run: |
          ./scripts/run_smoke_test.sh "res://addons/gut" "res://addons/debug_menu" "res://addons/input_remapper/test/create_default_schemes"

      - name: Discord notification
        if: ${{ env.SHOULD_SEND_DISCORD_MESSAGE == 'true' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ env.DISCORD_EMBEDS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ env.DISCORD_MESSAGE }}. Check the results in [this url](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."

  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: smoke-test
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Run test
        id: smoke-test
        run: |
          ./scripts/run_integration_tests.sh

      - name: Discord notification
        if: ${{ env.SHOULD_SEND_DISCORD_MESSAGE == 'true' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ env.DISCORD_MESSAGE }}. Check the results in [this url](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."

